name: restora
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.6
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.1.0
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  color: "#cf0e7a"
  image: assets/images/restora_cut.png
  color_dark: "#5f2a73"
  image_dark: assets/images/restora_cut.png



flutter:
  
  uses-material-design: true

  assets:
    - assets/images/