// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD42eG9w5ZFCW9goOW40ibUWhEUFLgwFE',
    appId: '1:480913986049:web:e356beffbde219c956e600',
    messagingSenderId: '480913986049',
    projectId: 'restora-58176',
    authDomain: 'restora-58176.firebaseapp.com',
    storageBucket: 'restora-58176.appspot.com',
    measurementId: 'G-83N2R1ZR93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCmd8cHOVnH9sNVlcCzAumUM3gKOGepLc',
    appId: '1:480913986049:android:99ee441deec67e9256e600',
    messagingSenderId: '480913986049',
    projectId: 'restora-58176',
    storageBucket: 'restora-58176.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5WbRtapup5KVomLGTGbsnlwBJwKK5k1E',
    appId: '1:480913986049:ios:17d798cb13ea832a56e600',
    messagingSenderId: '480913986049',
    projectId: 'restora-58176',
    storageBucket: 'restora-58176.appspot.com',
    iosClientId: '480913986049-5radr5ev84h84ojg9fiqkmfg1irh1c5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.restora',
  );
}
